config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  
  devise_for :users
  
  resources :users, only: [ :index ]
  resources :posts
  resources :relationships, only: [ :create, :destroy ]
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  # dbのlimit制約が効いてなかった
  # モデルでバリデーションするように
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  def unfollow(id)
    Relationship.find(id).destroy!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pagy::Backend
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :index  ]
  before_action :set_post, only: %i[edit update show]
  before_action :correct_user, only: [ :edit, :update ]

  def index
    @pagy, @posts = pagy(Post.all)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(posts_params)
    if @post.save
      redirect_to posts_path, notice: "ポストを新規作成しました"
    else
      render :new, status: :unprocessable_entity, alert: "ポストを作成出来ませんでした。"
    end
  end

  def edit
  end

  def update
    if @post.update(posts_params)
      redirect_to posts_path, notice: "ポストを更新しました。"
    else
      render :new, status: :unprocessable_entity, alert: "ポストを更新出来ませんでした。"
    end
  end

  def show
  end

  def destroy
    # 人が書いた投稿が消せてしまう
    Post.find(params[:id]).destroy!
    redirect_to posts_path, notice: "ポストを削除しました。"
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def posts_params
      params.require(:post).permit(:content)
    end

    def correct_user
      user = User.find(@post.user_id)
      redirect_to posts_path, alert: "ポストの作成者のみ編集可能です" unless user == current_user
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:id])
    redirect_to users_path
  end

  def destroy
    current_user.unfollow(params[:id])
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [ :index  ]

  def index
    @pagy, @users = pagy(User.all)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/_header.html.haml
- if user_signed_in?
  .container 
    ログイン中: 
    = current_user.email
  .container 
    = link_to('ユーザー一覧', users_path)
    = link_to('ポスト一覧', posts_path)
- else
  = link_to('新規ユーザー登録', new_user_registration_path)
  = link_to('ログイン', new_user_session_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Miniblog 2"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %div.container
      = render 'layouts/header'
      = flash.notice
      = flash.alert
      = yield

app/views/posts/_form.html.haml
-# パーシャルではインスタンス変数をつかわないように
= simple_form_for post do |f|
  = f.input :content
  = f.button :submit

app/views/posts/_toindex.html.haml
%div
  = link_to('Post一覧へ戻る', posts_path)

app/views/posts/edit.html.haml
= render 'toindex'
%h1 エディット画面
%div
  編集前:
  = @post.content
= render 'form', post: @post

app/views/posts/index.html.haml
%h1 ポスト一覧
= link_to "新規作成",new_post_path
%ul
  - @posts.each do |post|
    %li
      = post.id
      = post.content
      = link_to '詳細',post_path(post.id)
      -# 投稿者以外は編集・削除できないようにしたい
      = link_to '編集',edit_post_path(post.id)
      = link_to '削除', post_path(post), data: { turbo_method: :delete, turbo_confirm: "削除します、よろしいですか？" }
= pagy_bootstrap_nav(@pagy).html_safe

app/views/posts/new.html.haml
-# header パーシャルにリンクがあるので不要そう
= render = render 'toindex'
%h1 新規ポスト作成
= render 'form', post: @post

app/views/posts/show.html.haml
= render 'toindex'
%h1 ポスト詳細

-# post.idはユーザーに必要？
%div
  ID:
  = @post.id
%div
  content:
  = @post.content

-# だいたい投稿日時を表示するサイトが多いと思う
%div
  created_at:
  = @post.created_at
%div
  updated_at:
  = @post.updated_at

app/views/users/_follow_button.html.haml
-# 自分自身もフォローできてしまう
-# ２０人表示で２０クエリ実行されてそう
-# コントローラで取っておく↓
-# @follower_ids = current_user.active_relationships.pluck(:followed_id)
-# follower_ids.exists?(user_id) でフォロー中かを確認する
- relationship = current_user.active_relationships.find_by(followed_id: user_id)
- if relationship
  = button_to 'フォロー解除', relationship_path(id: relationship.id), method: :delete
- else
  = button_to 'フォロー', relationships_path, method: :post, params: {id: user_id}

app/views/users/index.html.haml
%h1 ユーザー一覧
%ul
  - @users.each do |user|
    %li
      = user.email
      = render 'follow_button', user_id: user.id
= pagy_bootstrap_nav(@pagy).html_safe